### PR TITLE
Remove varnish-sys

### PR DESCRIPTION
**Pull request by nyurik**
Moved all buindings to `crate::raw` (initially i used `varnish_sys` as a submodule, but the full path is a bit weird - `varnish::varnish_sys::*`, so `raw` is shorter.

Also, I searched github for `include!(concat!(env!("OUT_DIR"), "/bindings.rs"));`, and I noticed `raw`, `ffi`, `bindings`, and project specific words like `gl` being used for the submodule name.

Lastly, I used `cargo +nightly fmt --all -- --config imports_granularity=Module,group_imports=StdExternalCrate` to reformat all the use statements - keeps them a bit cleaner.

### CODE REVIEW

**Comment by gquintard** [comment]
I need to ruminate this one a bit (and conflicts need to be fixed) but it's a yes in principle

note: and I know I'm one to talk, but the PR would be easier to review if they were broken up in more or less atomic commits. We don't have a lot of traffic here, so I'm not going to be stringent about it, though.

**Comment by nyurik** [comment]
I agree about atomic commits - but this one is the smallest possible PR for merging it:  you must do the renaming in one go.  In theory, i could have kept the name `varnish_sys`, in which case i would have had to just add `use crate::varnish_sys` at the top of all files, and then later we could have renamed it, but that's the only change that can be optimized this way.

**Comment by gquintard** [comment]
not exactly true, there's a bunch of linting also happening all over the place. They don't have to be in the same commit.
Anyway, I don't want to sound ungrateful, I realy, really appreciate your work and attention here

**Comment by nyurik** [comment]
oh, i thought i kept these to minimum, sorry

**Comment by gquintard** [comment]
all good, no worries

**Comment by nyurik** [comment]
I rebased and renamed it back to `varnish_sys` -- this way we can refactor it separatelly.

**Comment by gquintard** [comment]
sweet, merging

**Pull request merged**
